name: Build and Publish supported.json

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Publish to release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin release:release || true
          git checkout -B release
          ./build.sh
          git add -f supported.json
          git commit -m "chore: update supported.json" || echo "No changes to commit"
          git push -f origin release
